### ISSUE TITLE
useDrizzleStudio breaks the non-dev build

### ISSUE THREAD

**Issue by psycho-baller** [drizzle-team/drizzle-studio-expo#1]
Drizzle studio works just as expected. As if I was using another non-local db, so tysm♥️ I'm lovin it. I even convinced [my team in IBM](https://github.com/ibm-skills-network) to use it over prisma😎 Anyways, here's the issue I'm facing:

I built my app using this command: `eas build --profile preview --platform android --local`

preview is basically the internal production build. This is my eas config:
```json
"preview": {
      "extends": "base",
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleRelease",
        "buildType": "apk"
      },
}
```
Build succeeds but when i try to open the app, I see this:
> ![image](https://github.com/drizzle-team/drizzle-studio-expo/assets/81759594/c9a79c30-e261-4263-95aa-286ad9ee9b0b)

Which I guess is coming from [here](https://github.com/drizzle-team/drizzle-studio-expo/blob/main/src/useDrizzleStudio.tsx#L6)
I can confirm that when I comment out the `useDrizzleStudio` hook, the app works fine in my preview build

Are we responsible to use this hook only in dev mode? or should this hook handle it? (would love to contribute)

The repo I'm using this in: https://github.com/psycho-baller/convo-topics/blob/local-db/packages/app/provider/expo-drizzle-studio/index.tsx

With love,
Rami :)

**Comment by dbrekelmans** [comment]
Same issue, would be great if the plugin handles this gracefully by checking the `__DEV__` global for example. More info here: https://docs.expo.dev/guides/tree-shaking/#remove-development-only-code

**Comment by hyoban** [comment]
You can refer to https://github.com/hyoban/follow-app/commit/e4f3ce985b44c61d86eba60eb8c7d06c3a2a26da to fix your code

**Comment by kimuradev** [comment]
I had similar issue and I solved using variable `EXPO_PUBLIC_DISABLE_FEATURE=true` to use drizzle studio only at development env.

```
 if (!process.env.EXPO_PUBLIC_DISABLE_FEATURE) {
        useDrizzleStudio(expoDb)
    }
 ```

**Comment by Kyrylo-Usichenko** [comment]
Fixed: environment validation has been added to the plugin.
